import {
	CalendarIcon,
	CalendarTimeOffIcon,
	CommunityIcon,
	FlowIcon,
	InboxIcon,
	NotesIcon,
	NotificationIcon,
	ProjectIcon,
	ReportsIcon,
	TasksIcon,
	TeamCloudIcon,
	TrashIcon,
} from "@/pages/authenticated/components/sidebar/icons/icons.ts";
export const Icons = {
	Notification: <NotificationIcon />,
	Tasks: <TasksIcon />,
	Notes: <NotesIcon />,
	Project: <ProjectIcon />,
	Reports: <ReportsIcon />,
	Flow: <FlowIcon />,
	TeamCloud: <TeamCloudIcon />,
	Trash: <TrashIcon />,
	Inbox: <InboxIcon />,
	Calendar: <CalendarIcon />,
	TimeOff: <CalendarTimeOffIcon />,
	Community: <CommunityIcon />,
};
